### ISSUE TITLE
Alias causing some trouble

### ISSUE THREAD

**Issue by cyqsimon** [KSXGitHub/ibus-daemon.pkgbuild#3]
Seems like `Alias=input-method.service` is causing some trouble with systemd:

```bash
$ enable-ibus-daemon --now
Failed to enable unit: Cannot alias ibus@:0.service as input-method.service.
```

I've searched `/usr/lib/systemd`, `/run/systemd`, `/etc/systemd`, and my entire home directory for any files named `input-method` and found nothing. So it doesn't seem to be an alias conflict issue, but I could be wrong.

---

For now I've disabled the alias with a drop-in file and it works fine again:

```bash
$ cat /etc/systemd/user/ibus@.service.d/disable-alias.conf
# disable service alias, otherwise systemd errors

[Install]
Alias=
```

But I don't think this is ideal, and I would like to learn about the root cause of this issue too. Could you please help investigate what's the problem here? Thanks.

**Comment by KSXGitHub** [comment]
Hmm, it seems that the script `enable-ibus-daemon` doesn't work for me too. The daemon itself works though, just need to reboot. Maybe it's time to remove `enable-ibus-daemon`?

**Comment by cyqsimon** [comment]
So I did some investigating. It seems like `Alias=input-method.service` is the problem here and should be removed/disabled.

According to `man systemd.unit`:
> systemd does not look at the [Install] section at all during normal operation, so any directives in that section only have an effect through the symlinks created during enablement.

This is why the daemon works after reboot: `systemctl --user enable` fails because it not create the symlink `~/.config/systemd/user/default.target.wants/input-method.service` (or whatever path it actually is), but did successfully create the symlink `~/.config/systemd/user/default.target.wants/ibus@:0.service`. Therefore although the command failed, the unit is actually enabled despite the alias not working.

As of why it couldn't be aliased, I later found why in the man page too:
> Aliases obey the following restrictions: a unit of a certain type (".service", ".socket", ...)
       can only be aliased by a name with the same type suffix. A plain unit (not a template or an
       instance), may only be aliased by a plain name. A template instance may only be aliased by
       another template instance, and the instance part must be identical. A template may be aliased by
       another template (in which case the alias applies to all instances of the template). As a
       special case, a template instance (e.g.  "alias@inst.service") may be a symlink to different
       template (e.g.  "template@inst.service"). In that case, just this specific instance is aliased,
       while other instances of the template (e.g.  "alias@foo.service", "alias@bar.service") are not
       aliased.

So unless something critically depends on the existence of `Alias=input-method.service` (in which case we need to find a workaround), this alias should be removed.

---

As of `enable-ibus-daemon`, I don't see anything wrong with it. It's a nice quality-of-life thing to have IMO.

**Comment by KSXGitHub** [comment]
Thank you for your investigation.

I have a question about this part:

> A template may be aliased by
> another template (in which case the alias applies to all instances of the template). As a
> special case, a template instance (e.g. "[alias@inst.service](mailto:alias@inst.service)") may be a symlink to different
> template (e.g. "[template@inst.service](mailto:template@inst.service)").

Does this means that `Alias=input-method@.service` will also work?

Although, I have forgotten why I put the alias there in the first place. Maybe it was because I copy-pasted a solution from StackOverflow.

**Comment by cyqsimon** [comment]
> Does this means that `Alias=input-method@.service` will also work?

Not sure. It's either `Alias=input-method@.service` or `Alias=input-method@%I.service`, or possibly both

If you cannot recall a specific reason why it's there, I think it's most likely okay to simply delete it.
